### ISSUE TITLE
vs2019无法使用吗？安装以后找不到插件

### ISSUE THREAD

**Issue by xiaoyutx94** [TimChen44/CCodeAI#12]
扩展管理器里面看到已安装，但是右键和工具里面都没看到。

**Comment by xiaoyutx94** [comment]
![image](https://github.com/TimChen44/CCodeAI/assets/5671609/f759f913-5b6d-400e-9921-adf0645b9ab6)

**Comment by weianweigan** [comment]
可能是codeanalysis 包的版本太高，导致和2019有冲突。设置兼容vs版本的时候把2019也加入了。

**Comment by weianweigan** [comment]
> ![image](https://github.com/TimChen44/CCodeAI/assets/5671609/f759f913-5b6d-400e-9921-adf0645b9ab6)
> 
> 

用2022吧，64位VS 值得拥有

**Comment by xiaoyutx94** [comment]
> > ![image](https://user-images.githubusercontent.com/5671609/240549736-f759f913-5b6d-400e-9921-adf0645b9ab6.png)
> 
> 用2022吧，64位VS 值得拥有

2022就是有些老的com组件没法使用了。
了解了，谢谢。
