### ISSUE TITLE
Slow downloads

### ISSUE THREAD

**Issue by prpt0405** [TimChen44/CCodeAI#13]
可不可以搞个浏览器下载的  公司下载visual studio扩展好慢

**Comment by weianweigan** [comment]
> You can download it from [visual studio markertplace online](https://marketplace.visualstudio.com/items?itemName=TimChen44.CCodeAI) from browser if you get a error when download it from visual studio.

![image](https://github.com/TimChen44/CCodeAI/assets/25452811/7dbf8397-6746-4360-b4f6-e77f419245f9)

**Comment by prpt0405** [comment]
![image](https://github.com/TimChen44/CCodeAI/assets/76674786/f478777b-bc3e-403e-b031-923280ca3e00)
Equally slow.

**Comment by weianweigan** [comment]
> ![image](https://user-images.githubusercontent.com/76674786/240831526-f478777b-bc3e-403e-b031-923280ca3e00.png) Equally slow.

Try this link. 
[Download CCodeAI.zip](https://github.com/TimChen44/CCodeAI/files/11562186/CCodeAI.zip)

**Comment by prpt0405** [comment]
> > ![图像](https://user-images.githubusercontent.com/76674786/240831526-f478777b-bc3e-403e-b031-923280ca3e00.png)同样慢。
> 
> 试试这个链接。 [下载CCodeAI.zip](https://github.com/TimChen44/CCodeAI/files/11562186/CCodeAI.zip)

a little better,three times much as that one.

**Comment by weianweigan** [comment]
> > > ![图像](https://user-images.githubusercontent.com/76674786/240831526-f478777b-bc3e-403e-b031-923280ca3e00.png)同样慢。
> > 
> > 
> > 试试这个链接。 [下载CCodeAI.zip](https://github.com/TimChen44/CCodeAI/files/11562186/CCodeAI.zip)
> 
> a little better,three times much as that one.

Try this onedrive link.

[CCodeAI](https://sncz4-my.sharepoint.com/:u:/g/personal/weigan_sncz4_onmicrosoft_com/EcojezTh6yNCllzZx7MRNggB_A3Y5qZFk35SPmL1gU1Y4A?e=vzvdLv)

**Comment by prpt0405** [comment]
> > > > ![图像](https://user-images.githubusercontent.com/76674786/240831526-f478777b-bc3e-403e-b031-923280ca3e00.png)同样慢。
> > > 
> > > 
> > > 试试这个链接。 [下载CCodeAI.zip](https://github.com/TimChen44/CCodeAI/files/11562186/CCodeAI.zip)
> > 
> > 
> > a little better,three times much as that one.
> 
> Try this onedrive link.
> 
> [CCodeAI](https://sncz4-my.sharepoint.com/:u:/g/personal/weigan_sncz4_onmicrosoft_com/EcojezTh6yNCllzZx7MRNggB_A3Y5qZFk35SPmL1gU1Y4A?e=vzvdLv)

Awesome！
