### ISSUE TITLE
Use markdown render control for chat history and FauxPilot

### ISSUE THREAD

**Issue by weianweigan** [TimChen44/CCodeAI#2]
# Markdown

In current chat history , there is a wpf textbox used in block. Could it replaced by markdown render control ?

* [markdown library](https://github.com/theunrepentantgeek/Markdown.XAML)

![image](https://user-images.githubusercontent.com/25452811/234303259-f4a99957-6ffd-4f8c-90a4-d8691da09bd8.png)

# [FauxPilot](https://github.com/fauxpilot/fauxpilot)

There is an open-source alternative to GitHub Copilot server. For this project, is it possible to use fauxpilot as another backend so it can generate more powerful code for user?

**Comment by TimChen44** [comment]
We can consider replacing him with a better Markdown editor.

I don't have much research on FauPilot, and I'm not sure if I want to join him at the moment.

I am currently studying SemanticKernel and preparing to use it for some necessary modifications。

however 我们能用中文聊😁，最后谢谢你的建议。

**Comment by weianweigan** [comment]
哈哈，semantical kernel从.netstandard2.1切换到2.0了，支持net48，应该可以接入到visual studio了
