### ISSUE TITLE
回复不完整的，有没有办法让他自动再次回复

### ISSUE THREAD

**Issue by monsm** [TimChen44/CCodeAI#6]
我现在是手动发‘继续’

**Comment by weianweigan** [comment]
是聊天窗口回答不完整吗？聊天配置回答限制在了2000个token

**Comment by monsm** [comment]
一个回答被切分了，需要再次发送继续才会回复没有回复完的

**Comment by weianweigan** [comment]
> 一个回答被切分了，需要再次发送继续才会回复没有回复完的

应该是回答限制在了2000个token，后面版本使用自己的APIkey的情况下应该放开这个限制
