### ISSUE TITLE
AzureConfig.cs 文件缺失

### ISSUE THREAD

**Issue by xbotter** [TimChen44/CCodeAI#9]
https://github.com/TimChen44/CCodeAI/blob/22803ed8a1a73fea6948f460e67ddbe9b53cb49f/.gitignore#L353

我想尝试在本地调试该项目，但是代码Clone下面之后发现缺少AzureConfig文件，看样子是存放了机密信息，不知道能不能脱敏后开放一下。

**Comment by weianweigan** [comment]
你可以参考一下GitHub action里的格式

public static class AzureConfig{public const string Endpoint = `"${{ secrets.ENDPOINT }}`";public const string AppKey = `"${{ secrets.APP_KEY }}`";}

https://github.com/TimChen44/CCodeAI/blob/main/.github/workflows/Build.yml
